### ISSUE TITLE
some toaplan1.cpp games won't start, jumps back to menu

### ISSUE THREAD

**Issue by asche76** [arcadeforge/regamebox_mme4crt#5]
fba: vimana (57.61 Hz), out zone (55.16 Hz) and some other toaplan1.cpp games won't start, jumps back to menu.
this appears only with mme4crt. with other/older methods they start as usual.
truxton (57.61 Hz, same driver) curiously works as usual.

**Comment by arcadeforge** [comment]
Which games should I try?

**Comment by arcadeforge** [comment]
Extended one if statement from 56 to 55, modified height for <55hz games
